name: blackbox_db
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Get images from assets
  path_provider: ^2.1.1

  # Date Formatter
  intl: ^0.19.0

  # Font style
  google_fonts: ^6.1.0
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

  # Save Data
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  shared_preferences: ^2.3.4
  
  # Svg support
  flutter_svg: ^2.0.9

  # State Management
  provider: ^6.1.2
  equatable: ^2.0.5
  
  # Responsive
  flutter_screenutil: ^5.9.0

  # GetX 
  get: ^4.6.6

  # Splash Screen
  flutter_native_splash: ^2.4.1

  # Permissions
  permission_handler: ^11.0.1

  # Get device info
  device_info_plus: ^10.1.2

  # Rename App
  rename_app: ^1.6.1

  # Auto Size Text
  auto_size_text: ^3.0.0

  # Rating
  flutter_rating_bar: ^4.0.1

  # Http
  dio: ^5.7.0

  # Cache Network Image 
  cached_network_image: ^3.4.0

  # shimmer
  shimmer: ^3.0.0

  # Windows window manager
  window_manager: ^0.4.3

  # Charts
  fl_chart: ^0.70.0
  syncfusion_flutter_charts: ^28.1.35

  # Secret key
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.8

  # Change App Package Name
  change_app_package_name: ^1.4.0

  flutter_lints: ^5.0.0

  # setup file
  msix: ^3.16.8

# # Splash Screen Settings
# flutter_native_splash:
#   color: "#000000" # Arka plan rengi
#   image: assets/images/SplashScreen/facelog600.png # Splash görüntüsü
#   android_12:
#     image: assets/images/SplashScreen/facelog1152.png # Android 12+ için splash görüntüsü
#     color: "#000000" # Arka plan rengi
  
# flutter_icons:
#   image_path: "assets/images/playstore.png"
#   android: true
#   ios: true
#   adaptive_icon_background: "#ffffff"
#   adaptive_icon_foreground: "assets/images/logo-foreground.png"

msix_config:
  display_name: BlackBox DB
  publisher_display_name: Kargalar
  identity_name: kargalar.blackboxdb
  msix_version: 1.0.0.0
  # logo_path: C:\KARGALAR\Downloads\Frame 13.png
  capabilities: internetClient

flutter:
  uses-material-design: true

  assets:
    - .env
  #   - assets/test/Book/
  #   - assets/test/Game/
  
  
  # fonts:
  #   - family: FacelogIcon
  #     fonts:
  #       - asset: assets\icons\FacelogIcon.ttf