// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl6RTXg-KnyORK51Rult69lFzU9qY6y4Q',
    appId: '1:38141671085:web:e40387d5c64ac4ea567824',
    messagingSenderId: '38141671085',
    projectId: 'blackboxdb-ec2f1',
    authDomain: 'blackboxdb-ec2f1.firebaseapp.com',
    storageBucket: 'blackboxdb-ec2f1.firebasestorage.app',
    measurementId: 'G-XCV5FVW7RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu8-dEBECf8DXOJL2oUIXeUXXw00H66Z4',
    appId: '1:38141671085:android:fe4e727fc907b06e567824',
    messagingSenderId: '38141671085',
    projectId: 'blackboxdb-ec2f1',
    storageBucket: 'blackboxdb-ec2f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuYQ0fbelj2QnUq0tRNRmkMp2sMwYV2U4',
    appId: '1:38141671085:ios:c7eb4eb8f424622f567824',
    messagingSenderId: '38141671085',
    projectId: 'blackboxdb-ec2f1',
    storageBucket: 'blackboxdb-ec2f1.firebasestorage.app',
    iosBundleId: 'com.example.blackboxDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuYQ0fbelj2QnUq0tRNRmkMp2sMwYV2U4',
    appId: '1:38141671085:ios:c7eb4eb8f424622f567824',
    messagingSenderId: '38141671085',
    projectId: 'blackboxdb-ec2f1',
    storageBucket: 'blackboxdb-ec2f1.firebasestorage.app',
    iosBundleId: 'com.example.blackboxDb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl6RTXg-KnyORK51Rult69lFzU9qY6y4Q',
    appId: '1:38141671085:web:aca31e1e00364a9c567824',
    messagingSenderId: '38141671085',
    projectId: 'blackboxdb-ec2f1',
    authDomain: 'blackboxdb-ec2f1.firebaseapp.com',
    storageBucket: 'blackboxdb-ec2f1.firebasestorage.app',
    measurementId: 'G-H8VZ5YXZ1E',
  );
}
