// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCodQE06pMmTAoL-Cuw7ksrlq52mYYA5kU',
    appId: '1:852342726064:web:d86f594248c0f4becf8a75',
    messagingSenderId: '852342726064',
    projectId: 'blackboxdb-d5e63',
    authDomain: 'blackboxdb-d5e63.firebaseapp.com',
    storageBucket: 'blackboxdb-d5e63.firebasestorage.app',
    measurementId: 'G-CCG3FWXL6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5lSvv8BiVJ4qE06dIdMRTbh_5ruHWZrU',
    appId: '1:852342726064:android:2d5ebb91c9d2e930cf8a75',
    messagingSenderId: '852342726064',
    projectId: 'blackboxdb-d5e63',
    storageBucket: 'blackboxdb-d5e63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBimsRgfvkUdwpv6eInmK8Qky2t2c8CwZo',
    appId: '1:852342726064:ios:81357b9393e54840cf8a75',
    messagingSenderId: '852342726064',
    projectId: 'blackboxdb-d5e63',
    storageBucket: 'blackboxdb-d5e63.firebasestorage.app',
    iosBundleId: 'app.blacboxDB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBimsRgfvkUdwpv6eInmK8Qky2t2c8CwZo',
    appId: '1:852342726064:ios:27bf9bb82f206253cf8a75',
    messagingSenderId: '852342726064',
    projectId: 'blackboxdb-d5e63',
    storageBucket: 'blackboxdb-d5e63.firebasestorage.app',
    iosBundleId: 'app.blacboxDB',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCodQE06pMmTAoL-Cuw7ksrlq52mYYA5kU',
    appId: '1:852342726064:web:3ad4255c4f067d6dcf8a75',
    messagingSenderId: '852342726064',
    projectId: 'blackboxdb-d5e63',
    authDomain: 'blackboxdb-d5e63.firebaseapp.com',
    storageBucket: 'blackboxdb-d5e63.firebasestorage.app',
    measurementId: 'G-QPN6EBCNEG',
  );
}
