-- Hızlı çözüm: RLS'yi tamamen kapat - TÜM TABLOLAR

-- Ana tablolar
ALTER TABLE app_user DISABLE ROW LEVEL SECURITY;
ALTER TABLE content DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_content_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE review DISABLE ROW LEVEL SECURITY;
ALTER TABLE review_comment DISABLE ROW LEVEL SECURITY;
ALTER TABLE review_like DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_follow DISABLE ROW LEVEL SECURITY;
ALTER TABLE list_movie DISABLE ROW LEVEL SECURITY;

-- Lookup tablolar
ALTER TABLE content_type_lookup DISABLE ROW LEVEL SECURITY;
ALTER TABLE content_status_lookup DISABLE ROW LEVEL SECURITY;

-- Film ile ilgili tablolar
ALTER TABLE m_genre DISABLE ROW LEVEL SECURITY;
ALTER TABLE m_director DISABLE ROW LEVEL SECURITY;
ALTER TABLE m_cast DISABLE ROW LEVEL SECURITY;
ALTER TABLE m_platform DISABLE ROW LEVEL SECURITY;
ALTER TABLE m_country DISABLE ROW LEVEL SECURITY;
ALTER TABLE m_language DISABLE ROW LEVEL SECURITY;
ALTER TABLE m_theme DISABLE ROW LEVEL SECURITY;

-- Oyun ile ilgili tablolar
ALTER TABLE g_genre DISABLE ROW LEVEL SECURITY;
ALTER TABLE g_director DISABLE ROW LEVEL SECURITY;
ALTER TABLE g_platform DISABLE ROW LEVEL SECURITY;
ALTER TABLE g_country DISABLE ROW LEVEL SECURITY;
ALTER TABLE g_language DISABLE ROW LEVEL SECURITY;
ALTER TABLE g_theme DISABLE ROW LEVEL SECURITY;

-- Film cross-reference tablolar
ALTER TABLE x_movie_genre DISABLE ROW LEVEL SECURITY;
ALTER TABLE x_movie_director DISABLE ROW LEVEL SECURITY;
ALTER TABLE x_movie_cast DISABLE ROW LEVEL SECURITY;
ALTER TABLE x_movie_platform DISABLE ROW LEVEL SECURITY;
ALTER TABLE x_movie_country DISABLE ROW LEVEL SECURITY;
ALTER TABLE x_movie_language DISABLE ROW LEVEL SECURITY;
ALTER TABLE x_movie_theme DISABLE ROW LEVEL SECURITY;

-- Oyun cross-reference tablolar
ALTER TABLE x_game_genre DISABLE ROW LEVEL SECURITY;
ALTER TABLE x_game_director DISABLE ROW LEVEL SECURITY;
ALTER TABLE x_game_platform DISABLE ROW LEVEL SECURITY;
ALTER TABLE x_game_country DISABLE ROW LEVEL SECURITY;
ALTER TABLE x_game_language DISABLE ROW LEVEL SECURITY;
ALTER TABLE x_game_theme DISABLE ROW LEVEL SECURITY;